name: Scraper

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle (raccomandato)
        uses: gradle/actions/setup-gradle@v3

      - name: Rendi gradlew eseguibile
        run: chmod +x ./gradlew

      - name: Build progetto (modulo app)
        run: ./gradlew :app:build

      - name: Esegui SkyStreaming scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          ./gradlew :app:run
          mv app/movies.m3u8 movies.m3u8

      - name: Commit e push del file M3U8 aggiornato
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add movies.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true
